(()=>{
  const SOURCE='SKYBITS_LEGACY_DEEP_SCANNER';
  const clean=s=>String(s??'').replace(/\s+/g,' ').trim();
  const abs=u=>{try{return new URL(u,location.href).href}catch(e){return String(u||'')}};
  const looksSkybits=()=>{const text=(document.title+' '+location.hostname+' '+location.href+' '+(document.body?.innerText||'').slice(0,20000)).toLowerCase();return /skybits|fleetlocate/.test(text)||/\/api\/v1\/(asset|search|landmark)/i.test(location.href)||performance.getEntriesByType('resource').some(x=>/\/api\/v1\//i.test(x.name));};
  const api=async(path,opts={})=>{const r=await fetch(new URL(path,location.origin),{credentials:'include',...opts});const text=await r.text();let json=null;try{json=JSON.parse(text)}catch(e){}return{ok:r.ok,status:r.status,url:r.url,json,text:text.slice(0,500000)}};
  async function snapshot(){
    const resources=performance.getEntriesByType('resource').map(x=>({name:x.name,initiatorType:x.initiatorType,duration:x.duration,transferSize:x.transferSize}));
    const links=[...document.querySelectorAll('a[href]')].map(a=>({text:clean(a.innerText).slice(0,300),href:abs(a.getAttribute('href'))}));
    const scripts=[...document.scripts].map(s=>({src:abs(s.src),type:s.type||'',inline:s.src?'':String(s.textContent||'').slice(0,20000)}));
    const forms=[...document.forms].map(f=>({action:abs(f.action),method:f.method,inputs:[...f.elements].map(e=>({name:e.name,id:e.id,type:e.type,value:e.type==='password'?'[redacted]':String(e.value||'').slice(0,500)}))}));
    const storage={local:{},session:{}};
    for(const[k,obj]of[['local',localStorage],['session',sessionStorage]]){try{for(let i=0;i<obj.length;i++){const k2=obj.key(i),v=String(obj.getItem(k2)||'');storage[k][k2]=/pass|token|secret|authorization|api[-_]?key/i.test(k2)?'[redacted]':v.slice(0,30000)}}catch(e){}}
    let indexedDB=[];try{indexedDB=(await window.indexedDB.databases()).map(x=>({name:x.name,version:x.version}))}catch(e){}
    const endpointCandidates=new Set();const add=s=>{for(const m of String(s||'').matchAll(/(?:["'`])((?:\/api\/|api\/)[^"'`\\\s]{2,300})(?:["'`])/gi))endpointCandidates.add(m[1])};scripts.forEach(s=>add(s.inline));resources.forEach(r=>add(r.name));
    const scriptSamples=[];for(const u of scripts.map(s=>s.src).filter(u=>u&&new URL(u).origin===location.origin).slice(0,100)){try{const r=await fetch(u,{credentials:'include'}),t=await r.text();add(t);scriptSamples.push({url:u,status:r.status,length:t.length,apiHints:[...new Set(t.match(/\/api\/[^"'`\s)]+/gi)||[])].slice(0,500)})}catch(e){scriptSamples.push({url:u,error:String(e)})}}
    return{url:location.href,title:document.title,hostname:location.hostname,skybits:looksSkybits(),time:new Date().toISOString(),bodyText:clean(document.body?.innerText||'').slice(0,1000000),html:document.documentElement.outerHTML.slice(0,3000000),resources,links,scripts,forms,storage,indexedDB,endpointCandidates:[...endpointCandidates].slice(0,5000),scriptSamples};
  }
  async function inventory(){
    const out={summary:null,pages:[],assets:[],details:[],errors:[],started:new Date().toISOString()};
    const sr=await api('/api/v1/asset/group/summary');out.summary=sr.json||sr.text;const expected=Number(out.summary?.totalAssetCount||out.summary?.data?.totalAssetCount||0);let groupIds=[];
    const firstBody={page:1,size:100,filters:{assetIDs:null,assetGroupIDs:null,searchKeyword:null,sort:[{field:'custAssetID',order:'DESC'}]}};const first=await api('/api/v1/asset/group/detail-asset',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(firstBody)});const rows0=first.json?.data?.rows||first.json?.rows||first.json?.data||[];if(Array.isArray(rows0))out.assets.push(...rows0);const gs0=first.json?.data?.assetGroups||first.json?.assetGroups||[];if(Array.isArray(gs0))groupIds=gs0.map(g=>g.id||g.groupID).filter(Boolean);const sum=out.summary?.data||out.summary;if(!groupIds.length){const gs=sum?.groups||sum?.assetGroups||[];if(Array.isArray(gs))groupIds=gs.map(g=>g.id||g.groupID).filter(Boolean)}out.pages.push({page:1,status:first.status,count:Array.isArray(rows0)?rows0.length:0});
    const size=100,maxPages=Math.max(1,Math.ceil((expected||rows0.length||500)/size));
    if(groupIds.length){out.assets=[];for(let p=1;p<=maxPages;p++){try{const body={page:p,size,filters:{assetIDs:null,assetGroupIDs:groupIds,searchKeyword:null,sort:[{field:'custAssetID',order:'DESC'}]}};const r=await api('/api/v1/asset/group/detail-asset',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const rows=r.json?.data?.rows||r.json?.rows||[];out.pages.push({page:p,status:r.status,count:Array.isArray(rows)?rows.length:0});if(Array.isArray(rows))out.assets.push(...rows);if(!Array.isArray(rows)||rows.length<size)break}catch(e){out.errors.push('detail page '+p+': '+e);break}}}
    const ids=[...new Set(out.assets.map(x=>x?.custAssetID||x?.asset||x?.assetID).filter(Boolean))];for(let i=0;i<ids.length;i+=8){const rs=await Promise.all(ids.slice(i,i+8).map(async id=>{try{const r=await api('/api/v1/search/assets?keyword='+encodeURIComponent(id));return r.json?{source:'search',query:id,row:r.json}:null}catch(e){out.errors.push('search '+id+': '+e);return null}}));rs.filter(Boolean).forEach(x=>out.details.push(x))}
    const assetIds=[...new Set(out.assets.map(x=>x?.assetID).filter(Boolean))];for(let i=0;i<assetIds.length;i+=4){const rs=await Promise.all(assetIds.slice(i,i+4).map(async id=>{try{const r=await api('/api/v1/asset/asset360view/'+encodeURIComponent(id));return r.json?{source:'asset360view',assetID:id,data:r.json}:null}catch(e){out.errors.push('360 '+id+': '+e);return null}}));rs.filter(Boolean).forEach(x=>out.details.push(x))}
    return{...out,expected,groupIds,finished:new Date().toISOString()};
  }
  const network=[];window.addEventListener('message',e=>{if(e.source===window&&e.data?.source===SOURCE){const p=e.data.payload;network.push(p);if(network.length>2000)network.shift();chrome.runtime.sendMessage({cmd:'recordNetwork',payload:p}).catch(()=>{})}});
  setTimeout(()=>{if(looksSkybits())chrome.runtime.sendMessage({cmd:'recordPage'}).catch(()=>{})},1200);
  chrome.runtime.onMessage.addListener((m,s,send)=>{(async()=>{if(m?.cmd==='scanPage')return{kind:'page',snapshot:await snapshot(),network:network.slice()};if(m?.cmd==='scanInventory')return{kind:'inventory',...(await inventory())};if(m?.cmd==='isSkybits')return{skybits:looksSkybits(),url:location.href};throw Error('Unknown command')})().then(send).catch(e=>send({error:String(e)}));return true});
})();
