let last=null;const $=id=>document.getElementById(id);const status=s=>$('status').textContent=s;const busy=v=>$('prog').style.width=v?'80%':'0%';
function send(cmd,extra={}){return new Promise((res,rej)=>chrome.runtime.sendMessage({cmd,...extra},r=>{if(chrome.runtime.lastError)rej(chrome.runtime.lastError);else if(r?.error)rej(new Error(r.error));else res(r)}))}
async function refresh(){try{const s=await send('getRecorderStatus');$('auto').textContent=s.autoRecord?'AUTO RECORDING: ON':'AUTO RECORDING: OFF';$('auto').className='btn '+(s.autoRecord?'on':'off');$('count').textContent=`Saved records: ${Number(s.records||0).toLocaleString()}`}catch(e){}}
$('auto').onclick=async()=>{try{const s=await send('getRecorderStatus');await send('setRecorder',{value:!s.autoRecord});status(!s.autoRecord?'Automatic recording enabled.':'Automatic recording paused.');await refresh()}catch(e){status('ERROR: '+e.message)}};
$('page').onclick=async()=>{busy(1);status('Scanning the complete current Skybits page...');try{last=await send('scanCurrent');status(`DONE\nSkybits: ${last.page?.snapshot?.skybits}\nHTML: ${(last.page?.snapshot?.html?.length||0).toLocaleString()} chars\nResources: ${last.page?.snapshot?.resources?.length||0}\nLinks: ${last.page?.snapshot?.links?.length||0}\nAPI network records: ${last.network?.length||0}\nAPI candidates found in scripts: ${last.page?.snapshot?.endpointCandidates?.length||0}`)}catch(e){status('ERROR: '+e.message)}finally{busy(0);refresh()}};
$('all').onclick=async()=>{busy(1);status('Scanning ALL discovered Skybits loads/assets. This may take several minutes...');try{last=await send('scanAll');const i=last.inventory||{};status(`DONE\nExpected assets: ${i.expected||'?'}\nAssets collected: ${i.assets?.length||0}\nDetail records: ${i.details?.length||0}\nInventory pages: ${i.pages?.length||0}\nErrors: ${i.errors?.length||0}`)}catch(e){status('ERROR: '+e.message)}finally{busy(0);refresh()}};
$('tabs').onclick=async()=>{busy(1);status('Finding same-origin Skybits pages, opening them in background tabs, scanning, then closing them...');try{last=await send('openAndScan');status(`DONE\nPages scanned: ${last.count}\nTemporary tabs were closed.`)}catch(e){status('ERROR: '+e.message)}finally{busy(0);refresh()}};
$('exportdb').onclick=async()=>{busy(1);status('Exporting the automatic discovery database...');try{const db=await send('exportDB');const b=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='skybits-legacy-discovery-database.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);status(`EXPORTED\nRecords: ${(db.recordCount||0).toLocaleString()}`)}catch(e){status('ERROR: '+e.message)}finally{busy(0)}};
$('cleardb').onclick=async()=>{if(!confirm('Delete the locally saved Skybits discovery database?'))return;try{await send('clearDB');status('Discovery database cleared.');await refresh()}catch(e){status('ERROR: '+e.message)}};
$('json').onclick=()=>{if(!last){status('Run a scan first.');return}const b=new Blob([JSON.stringify(last,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='skybits-legacy-deep-scan.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
$('csv').onclick=()=>{const rows=last?.inventory?.assets||[];if(!rows.length){status('Run SCAN ALL LOADS first.');return}const keys=['custAssetID','assetID','assetType','mtsn','arrivedAtLandmarkMillisUTC','idleTimeHours','startedMovingFromMillisUTC','movingDurationMinutes','landmarkName','landmarkID','countryAbbr','stateAbbr','zip','city','sensorData','lastReportedTimeMillisUTC','mtid','geoClass','distanceFromLandmarkMiles','direction','assetGroups','aSeqNum'];const q=v=>'"'+String(typeof v==='object'?JSON.stringify(v):v??'').replaceAll('"','""')+'"';const out=[keys.join(',')].concat(rows.map(r=>keys.map(k=>q(r[k])).join(','))).join('\n');const b=new Blob([out],{type:'text/csv'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='skybits-loads.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
refresh();
